/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    breeds: Breed;
    comparisons: Comparison;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    breeds: BreedsSelect<false> | BreedsSelect<true>;
    comparisons: ComparisonsSelect<false> | ComparisonsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Dog and cat breed profiles with detailed traits and ratings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds".
 */
export interface Breed {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g. golden-retriever)
   */
  slug: string;
  petType: 'dog' | 'cat';
  status?: ('draft' | 'published') | null;
  featured?: boolean | null;
  image?: (number | null) | Media;
  /**
   * One-liner for cards and SEO (max 160 chars)
   */
  shortDescription?: string | null;
  breedGroup?:
    | (
        | 'sporting'
        | 'working'
        | 'herding'
        | 'toy'
        | 'terrier'
        | 'hound'
        | 'non-sporting'
        | 'foundation-stock'
        | 'natural'
        | 'hybrid'
        | 'mutation'
        | 'crossbreed'
      )
    | null;
  size?: ('small' | 'medium' | 'large' | 'giant') | null;
  heightMin?: number | null;
  heightMax?: number | null;
  weightMin?: number | null;
  weightMax?: number | null;
  lifeExpectancyMin?: number | null;
  lifeExpectancyMax?: number | null;
  coatType?:
    | ('smooth' | 'double' | 'wire' | 'curly' | 'silky' | 'hairless' | 'long' | 'short' | 'medium' | 'rough')
    | null;
  coatLength?: ('short' | 'medium' | 'long' | 'hairless') | null;
  colors?:
    | {
        color: string;
        id?: string | null;
      }[]
    | null;
  origin?: string | null;
  /**
   * e.g. "Retrieving game", "Herding sheep", "Companion"
   */
  breedRole?: string | null;
  /**
   * Key temperament descriptors (e.g. Loyal, Energetic, Gentle)
   */
  temperament?:
    | {
        trait: string;
        id?: string | null;
      }[]
    | null;
  strengths?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  weaknesses?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rate each trait from 1 (lowest) to 10 (highest). These power the breed comparison charts.
   */
  traits?: {
    /**
     * How loving and cuddly with family (1 = lowest, 10 = highest)
     */
    affectionLevel?: number | null;
    /**
     * Patience and safety around children (1 = lowest, 10 = highest)
     */
    childFriendly?: number | null;
    /**
     * Gets along with other dogs and cats (1 = lowest, 10 = highest)
     */
    petFriendly?: number | null;
    /**
     * How they react to new people (1 = lowest, 10 = highest)
     */
    strangerFriendly?: number | null;
    /**
     * Ease of training and willingness to learn (1 = lowest, 10 = highest)
     */
    trainability?: number | null;
    /**
     * Daily energy and exercise requirements (1 = lowest, 10 = highest)
     */
    energyLevel?: number | null;
    /**
     * Amount of grooming and maintenance required (1 = lowest, 10 = highest)
     */
    groomingNeeds?: number | null;
    /**
     * How much they shed (1 = lowest, 10 = highest)
     */
    sheddingLevel?: number | null;
    /**
     * Tendency to bark or vocalize (1 = lowest, 10 = highest)
     */
    barkingLevel?: number | null;
    /**
     * Problem-solving ability and learning speed (1 = lowest, 10 = highest)
     */
    intelligence?: number | null;
    /**
     * Play drive and fun factor (1 = lowest, 10 = highest)
     */
    playfulness?: number | null;
    /**
     * Alertness and protective instincts (1 = lowest, 10 = highest)
     */
    watchdogAbility?: number | null;
    /**
     * Adjusting to new environments and changes (1 = lowest, 10 = highest)
     */
    adaptability?: number | null;
    /**
     * Overall genetic health and disease resistance (1 = lowest, 10 = highest)
     */
    healthRobustness?: number | null;
  };
  /**
   * HTML content covering the breed's origin story and history
   */
  breedHistory?: string | null;
  /**
   * HTML article covering all traits in detail — temperament, health, exercise, diet, grooming, training, living conditions, and who this breed is for
   */
  article?: string | null;
  author?: string | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-generated head-to-head dog breed comparisons
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons".
 */
export interface Comparison {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short excerpt for SEO meta descriptions and cards
   */
  summary?: string | null;
  /**
   * Full article body as HTML
   */
  content?: string | null;
  /**
   * The breeds compared in this article (at least two)
   */
  breeds: (number | Breed)[];
  /**
   * Trait keys used by the comparison table. Leave empty to use defaults.
   */
  comparisonCriteria?:
    | {
        criterion:
          | 'lowShedding'
          | 'apartmentFriendly'
          | 'watchdogAbility'
          | 'energyLevel'
          | 'trainability'
          | 'childFriendly'
          | 'petFriendly'
          | 'easyGrooming'
          | 'barkingControl'
          | 'adaptability'
          | 'intelligence'
          | 'healthRobustness';
        id?: string | null;
      }[]
    | null;
  /**
   * Closing verdict block shown below the comparison table.
   */
  verdict?: string | null;
  author?: string | null;
  featuredImage?: (number | null) | Media;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'breeds';
        value: number | Breed;
      } | null)
    | ({
        relationTo: 'comparisons';
        value: number | Comparison;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds_select".
 */
export interface BreedsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  petType?: T;
  status?: T;
  featured?: T;
  image?: T;
  shortDescription?: T;
  breedGroup?: T;
  size?: T;
  heightMin?: T;
  heightMax?: T;
  weightMin?: T;
  weightMax?: T;
  lifeExpectancyMin?: T;
  lifeExpectancyMax?: T;
  coatType?: T;
  coatLength?: T;
  colors?:
    | T
    | {
        color?: T;
        id?: T;
      };
  origin?: T;
  breedRole?: T;
  temperament?:
    | T
    | {
        trait?: T;
        id?: T;
      };
  strengths?:
    | T
    | {
        point?: T;
        id?: T;
      };
  weaknesses?:
    | T
    | {
        point?: T;
        id?: T;
      };
  traits?:
    | T
    | {
        affectionLevel?: T;
        childFriendly?: T;
        petFriendly?: T;
        strangerFriendly?: T;
        trainability?: T;
        energyLevel?: T;
        groomingNeeds?: T;
        sheddingLevel?: T;
        barkingLevel?: T;
        intelligence?: T;
        playfulness?: T;
        watchdogAbility?: T;
        adaptability?: T;
        healthRobustness?: T;
      };
  breedHistory?: T;
  article?: T;
  author?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons_select".
 */
export interface ComparisonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  breeds?: T;
  comparisonCriteria?:
    | T
    | {
        criterion?: T;
        id?: T;
      };
  verdict?: T;
  author?: T;
  featuredImage?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}