/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    breeds: Breed;
    comparisons: Comparison;
    'quiz-questions': QuizQuestion;
    'quiz-submissions': QuizSubmission;
    'content-plan': ContentPlan;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    breeds: BreedsSelect<false> | BreedsSelect<true>;
    comparisons: ComparisonsSelect<false> | ComparisonsSelect<true>;
    'quiz-questions': QuizQuestionsSelect<false> | QuizQuestionsSelect<true>;
    'quiz-submissions': QuizSubmissionsSelect<false> | QuizSubmissionsSelect<true>;
    'content-plan': ContentPlanSelect<false> | ContentPlanSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Dog and cat breed profiles with detailed traits and ratings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds".
 */
export interface Breed {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g. golden-retriever)
   */
  slug: string;
  petType: 'dog' | 'cat';
  status?: ('draft' | 'published') | null;
  featured?: boolean | null;
  image?: (number | null) | Media;
  /**
   * One-liner for cards and SEO (max 160 chars)
   */
  shortDescription?: string | null;
  breedGroup?:
    | (
        | 'sporting'
        | 'working'
        | 'herding'
        | 'toy'
        | 'terrier'
        | 'hound'
        | 'non-sporting'
        | 'foundation-stock'
        | 'natural'
        | 'hybrid'
        | 'mutation'
        | 'crossbreed'
      )
    | null;
  size?: ('small' | 'medium' | 'large' | 'giant') | null;
  heightMin?: number | null;
  heightMax?: number | null;
  weightMin?: number | null;
  weightMax?: number | null;
  lifeExpectancyMin?: number | null;
  lifeExpectancyMax?: number | null;
  coatType?:
    | ('smooth' | 'double' | 'wire' | 'curly' | 'silky' | 'hairless' | 'long' | 'short' | 'medium' | 'rough')
    | null;
  coatLength?: ('short' | 'medium' | 'long' | 'hairless') | null;
  colors?:
    | {
        color: string;
        id?: string | null;
      }[]
    | null;
  origin?: string | null;
  /**
   * e.g. "Retrieving game", "Herding sheep", "Companion"
   */
  breedRole?: string | null;
  /**
   * Key temperament descriptors (e.g. Loyal, Energetic, Gentle)
   */
  temperament?:
    | {
        trait: string;
        id?: string | null;
      }[]
    | null;
  strengths?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  weaknesses?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rate each trait from 1 (lowest) to 10 (highest). These power the breed comparison charts.
   */
  traits?: {
    /**
     * How loving and cuddly with family (1 = lowest, 10 = highest)
     */
    affectionLevel?: number | null;
    /**
     * Patience and safety around children (1 = lowest, 10 = highest)
     */
    childFriendly?: number | null;
    /**
     * Gets along with other dogs and cats (1 = lowest, 10 = highest)
     */
    petFriendly?: number | null;
    /**
     * How they react to new people (1 = lowest, 10 = highest)
     */
    strangerFriendly?: number | null;
    /**
     * Ease of training and willingness to learn (1 = lowest, 10 = highest)
     */
    trainability?: number | null;
    /**
     * Daily energy and exercise requirements (1 = lowest, 10 = highest)
     */
    energyLevel?: number | null;
    /**
     * Amount of grooming and maintenance required (1 = lowest, 10 = highest)
     */
    groomingNeeds?: number | null;
    /**
     * How much they shed (1 = lowest, 10 = highest)
     */
    sheddingLevel?: number | null;
    /**
     * Tendency to bark or vocalize (1 = lowest, 10 = highest)
     */
    barkingLevel?: number | null;
    /**
     * Problem-solving ability and learning speed (1 = lowest, 10 = highest)
     */
    intelligence?: number | null;
    /**
     * Play drive and fun factor (1 = lowest, 10 = highest)
     */
    playfulness?: number | null;
    /**
     * Alertness and protective instincts (1 = lowest, 10 = highest)
     */
    watchdogAbility?: number | null;
    /**
     * Adjusting to new environments and changes (1 = lowest, 10 = highest)
     */
    adaptability?: number | null;
    /**
     * Overall genetic health and disease resistance (1 = lowest, 10 = highest)
     */
    healthRobustness?: number | null;
  };
  /**
   * HTML content covering the breed's origin story and history
   */
  breedHistory?: string | null;
  /**
   * HTML article covering all traits in detail — temperament, health, exercise, diet, grooming, training, living conditions, and who this breed is for
   */
  article?: string | null;
  author?: string | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-generated head-to-head dog breed comparisons
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons".
 */
export interface Comparison {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short excerpt for SEO meta descriptions and cards
   */
  summary?: string | null;
  /**
   * Full article body as HTML
   */
  content?: string | null;
  /**
   * The breeds compared in this article (at least two)
   */
  breeds: (number | Breed)[];
  /**
   * Trait keys used by the comparison table. Leave empty to use defaults.
   */
  comparisonCriteria?:
    | {
        criterion:
          | 'lowShedding'
          | 'apartmentFriendly'
          | 'watchdogAbility'
          | 'energyLevel'
          | 'trainability'
          | 'childFriendly'
          | 'petFriendly'
          | 'easyGrooming'
          | 'barkingControl'
          | 'adaptability'
          | 'intelligence'
          | 'healthRobustness';
        id?: string | null;
      }[]
    | null;
  /**
   * Closing verdict block shown below the comparison table.
   */
  verdict?: string | null;
  author?: string | null;
  featuredImage?: (number | null) | Media;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions for the Breed Match quiz, with trait weights per answer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions".
 */
export interface QuizQuestion {
  id: number;
  /**
   * The question as the visitor reads it. Keep it conversational.
   */
  question: string;
  /**
   * Optional one-liner under the question — context, or permission to be honest.
   */
  helper?: string | null;
  /**
   * Machine key used in stored answers (e.g. household-energy). Do not reuse.
   */
  key: string;
  /**
   * Lower numbers are asked first.
   */
  order: number;
  status?: ('draft' | 'published') | null;
  /**
   * Only ask this question when the visitor is after this kind of pet.
   */
  petScope?: ('both' | 'dog' | 'cat') | null;
  type?: ('single' | 'multi' | 'text') | null;
  /**
   * Grid for 4-6 rich options, list for wordy ones, scale for a 1-5 style row.
   */
  layout?: ('grid' | 'list' | 'scale') | null;
  /**
   * Shown above the question. One emoji.
   */
  emoji?: string | null;
  required?: boolean | null;
  /**
   * Pick Several only. Leave blank for no limit.
   */
  maxSelections?: number | null;
  /**
   * Free Text only.
   */
  placeholder?: string | null;
  /**
   * Each option nudges the match via its trait weights.
   */
  options?:
    | {
        /**
         * What the visitor clicks.
         */
        label: string;
        /**
         * Stored value (e.g. couch-potato).
         */
        value: string;
        /**
         * One emoji for the option tile.
         */
        emoji?: string | null;
        /**
         * Optional half-sentence under the label.
         */
        description?: string | null;
        /**
         * How this answer should shape the match.
         */
        weights?:
          | {
              trait:
                | 'affectionLevel'
                | 'childFriendly'
                | 'petFriendly'
                | 'strangerFriendly'
                | 'trainability'
                | 'energyLevel'
                | 'groomingNeeds'
                | 'sheddingLevel'
                | 'barkingLevel'
                | 'intelligence'
                | 'playfulness'
                | 'watchdogAbility'
                | 'adaptability'
                | 'healthRobustness';
              /**
               * The ideal score for this trait, 1-10.
               */
              target: number;
              /**
               * How much this matters, 1 (nudge) to 5 (dealbreaker).
               */
              weight: number;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional — breeds in these size bands get a bonus for this answer.
         */
        prefersSizes?: ('small' | 'medium' | 'large' | 'giant')[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The note this question was drafted from. Kept for context when reviewing.
   */
  sourceNote?: string | null;
  aiGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Completed Breed Match quiz runs, with the answers and what we recommended
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-submissions".
 */
export interface QuizSubmission {
  id: number;
  /**
   * Blank when the visitor skipped the email step.
   */
  email?: string | null;
  subscribed?: boolean | null;
  petType?: ('dog' | 'cat' | 'either') | null;
  /**
   * Fallback means Grok was unavailable and trait scoring decided the result.
   */
  matchedBy?: ('ai' | 'fallback') | null;
  topBreedName?: string | null;
  recommendedBreeds?: (number | Breed)[] | null;
  /**
   * Free-text the visitor added at the end. Raw material for new questions.
   */
  note?: string | null;
  /**
   * Every question asked and what they picked.
   */
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The full match payload returned to the visitor.
   */
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Where the quiz was started from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The rolling plan of articles the daily generator works through
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-plan".
 */
export interface ContentPlan {
  id: number;
  /**
   * A placeholder. The writer produces the real headline.
   */
  workingTitle: string;
  style: 'head-to-head' | 'three-way' | 'best-for' | 'group-roundup';
  status?: ('queued' | 'generated' | 'skipped' | 'failed') | null;
  /**
   * The daily job picks the oldest queued item due on or before today.
   */
  scheduledFor?: string | null;
  score?: number | null;
  /**
   * For roundups — the lifestyle angle, e.g. apartments. See lib/content-styles.ts.
   */
  angleKey?: string | null;
  /**
   * For group roundups — which group to cover.
   */
  breedGroup?: string | null;
  /**
   * Pre-picked for head-to-head and three-way. Roundups leave this empty and shortlist at generation time, so the picks reflect the latest ratings.
   */
  breeds?: (number | Breed)[] | null;
  /**
   * Optional override. Empty means the generator picks.
   */
  criteria?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * What the planner saw in this idea.
   */
  reason?: string | null;
  /**
   * Filled in once the daily job has written it.
   */
  generatedArticle?: (number | null) | Comparison;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'breeds';
        value: number | Breed;
      } | null)
    | ({
        relationTo: 'comparisons';
        value: number | Comparison;
      } | null)
    | ({
        relationTo: 'quiz-questions';
        value: number | QuizQuestion;
      } | null)
    | ({
        relationTo: 'quiz-submissions';
        value: number | QuizSubmission;
      } | null)
    | ({
        relationTo: 'content-plan';
        value: number | ContentPlan;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds_select".
 */
export interface BreedsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  petType?: T;
  status?: T;
  featured?: T;
  image?: T;
  shortDescription?: T;
  breedGroup?: T;
  size?: T;
  heightMin?: T;
  heightMax?: T;
  weightMin?: T;
  weightMax?: T;
  lifeExpectancyMin?: T;
  lifeExpectancyMax?: T;
  coatType?: T;
  coatLength?: T;
  colors?:
    | T
    | {
        color?: T;
        id?: T;
      };
  origin?: T;
  breedRole?: T;
  temperament?:
    | T
    | {
        trait?: T;
        id?: T;
      };
  strengths?:
    | T
    | {
        point?: T;
        id?: T;
      };
  weaknesses?:
    | T
    | {
        point?: T;
        id?: T;
      };
  traits?:
    | T
    | {
        affectionLevel?: T;
        childFriendly?: T;
        petFriendly?: T;
        strangerFriendly?: T;
        trainability?: T;
        energyLevel?: T;
        groomingNeeds?: T;
        sheddingLevel?: T;
        barkingLevel?: T;
        intelligence?: T;
        playfulness?: T;
        watchdogAbility?: T;
        adaptability?: T;
        healthRobustness?: T;
      };
  breedHistory?: T;
  article?: T;
  author?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons_select".
 */
export interface ComparisonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  breeds?: T;
  comparisonCriteria?:
    | T
    | {
        criterion?: T;
        id?: T;
      };
  verdict?: T;
  author?: T;
  featuredImage?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions_select".
 */
export interface QuizQuestionsSelect<T extends boolean = true> {
  question?: T;
  helper?: T;
  key?: T;
  order?: T;
  status?: T;
  petScope?: T;
  type?: T;
  layout?: T;
  emoji?: T;
  required?: T;
  maxSelections?: T;
  placeholder?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        emoji?: T;
        description?: T;
        weights?:
          | T
          | {
              trait?: T;
              target?: T;
              weight?: T;
              id?: T;
            };
        prefersSizes?: T;
        id?: T;
      };
  sourceNote?: T;
  aiGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-submissions_select".
 */
export interface QuizSubmissionsSelect<T extends boolean = true> {
  email?: T;
  subscribed?: T;
  petType?: T;
  matchedBy?: T;
  topBreedName?: T;
  recommendedBreeds?: T;
  note?: T;
  answers?: T;
  result?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-plan_select".
 */
export interface ContentPlanSelect<T extends boolean = true> {
  workingTitle?: T;
  style?: T;
  status?: T;
  scheduledFor?: T;
  score?: T;
  angleKey?: T;
  breedGroup?: T;
  breeds?: T;
  criteria?: T;
  reason?: T;
  generatedArticle?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}