/**
 * Works out which comparison articles are not worth indexing, and writes the
 * list to data/noindex-comparisons.json.
 *
 *   npx tsx scripts/compute-noindex.ts [--dry]
 *
 * Runs as part of `prebuild`, before Astro starts, because three separate
 * things need the same answer and must not disagree:
 *
 *   - the page, which emits <meta name="robots" content="noindex">
 *   - the sitemap, which must not submit a URL we are asking Google to ignore
 *   - the /compare index, which should not put the weakest pages on show
 *
 * Computing it once and writing it down is what keeps them consistent. A page
 * that says noindex while the sitemap submits it is a contradiction Google
 * reports as an error.
 *
 * Nothing is deleted. These URLs still resolve and still link out to the breed
 * profiles, so no inbound link or bookmark breaks; they simply stop being
 * offered to search engines and stop taking up space on the index page.
 */

import fs from 'node:fs';
import path from 'node:path';
import { assessDemand, demandSource } from '../src/lib/search-demand';
import { isRetired } from '../src/lib/retired';

const API = process.env.PAYLOAD_API_URL || 'http://127.0.0.1:3000/api';
const OUT = path.resolve(process.cwd(), 'data/noindex-comparisons.json');
const dry = process.argv.includes('--dry');

interface Row {
  slug: string;
  title: string;
  score: number;
  shape: string;
  breeds: string[];
}

async function main() {
  let docs: any[];
  try {
    const res = await fetch(`${API}/comparisons?where[status][equals]=published&limit=500&depth=1`, {
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    docs = (await res.json()).docs;
  } catch (e) {
    // The build can survive the CMS being down — it falls back to cached data —
    // so this must not fail the build. Keeping the previous list is right:
    // it is the last known-good answer.
    console.warn(`[noindex] CMS unavailable (${(e as Error).message}); keeping the existing list`);
    if (!fs.existsSync(OUT)) {
      fs.writeFileSync(OUT, JSON.stringify({ updated: null, slugs: [], note: 'CMS unavailable on first run' }, null, 2));
    }
    return;
  }

  const low: Row[] = [];
  let kept = 0;
  for (const doc of docs) {
    // Retired articles get no page at all, so there is nothing to noindex.
    if (isRetired(doc.slug)) continue;
    const breeds = (doc.breeds ?? [])
      .filter((b: unknown) => typeof b !== 'string')
      .map((b: any) => b.slug as string);
    const verdict = assessDemand(breeds, doc.title);
    if (verdict.lowDemand) {
      low.push({ slug: doc.slug, title: doc.title, score: verdict.score, shape: verdict.shape, breeds });
    } else {
      kept += 1;
    }
  }

  low.sort((a, b) => a.score - b.score || a.slug.localeCompare(b.slug));

  const payload = {
    updated: new Date().toISOString().slice(0, 10),
    demandData: demandSource(),
    kept,
    noindexed: low.length,
    note: 'Generated by scripts/compute-noindex.ts. Edit data/search-demand.json, not this file.',
    slugs: low.map((r) => r.slug),
    detail: low,
  };

  console.log(
    `[noindex] ${docs.length} published: ${kept} indexed, ${low.length} held back ` +
      `(demand data: ${payload.demandData.source}, ${payload.demandData.scored} breeds scored)`,
  );
  for (const r of low) console.log(`          ${String(r.score).padStart(3)}  ${r.slug}`);

  if (dry) {
    console.log('[noindex] --dry, not writing');
    return;
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(payload, null, 2) + '\n');
}

await main();
