/**
 * Emit the nginx map that redirects retired comparison URLs.
 *
 *   npx tsx scripts/generate-comparison-redirects.ts
 *   sudo cp deploy/nginx-comparison-redirects.conf \
 *     /etc/nginx/conf.d/zz-pawlabs-comparison-redirects.conf
 *   sudo nginx -t && sudo systemctl reload nginx
 *
 * A 301 rather than a noindex tag, because these pages are being withdrawn
 * rather than merely hidden: the redirect passes whatever link signal they had
 * to the ranking that covers the same breeds, and nothing is left behind for a
 * reviewer to sample. Nothing 404s.
 *
 * Generated from data/retired-comparisons.json — edit that, then re-run.
 */

import fs from 'node:fs';
import path from 'node:path';
import { retiredComparisons } from '../src/lib/retired';

/**
 * Deployed to /etc/nginx/conf.d/zz-pawlabs-comparison-redirects.conf — the
 * prefix matters, see the note in the generated header.
 */
const OUT = path.resolve(process.cwd(), 'deploy/nginx-comparison-redirects.conf');

const rows = retiredComparisons().filter((r) => r.redirectTo);
const skipped = retiredComparisons().filter((r) => !r.redirectTo);

const lines = [
  '# Retired comparison articles -> the ranking that covers the same breeds.',
  '#',
  '# Generated by scripts/generate-comparison-redirects.ts from',
  '# data/retired-comparisons.json. Do not edit by hand.',
  '#',
  '# These articles were withdrawn as combinatorial or negligible-demand pages.',
  '# The documents still exist in the CMS; the site simply stops building them.',
  `# Generated ${new Date().toISOString().slice(0, 10)} — ${rows.length} redirects.`,
  '',
  '# These slugs are long enough to need map_hash_bucket_size raised above the',
  '# 64-byte default. nginx rejects a duplicate declaration, and the media',
  '# redirects already set it, so this file must be *included after* that one —',
  '# hence the zz- prefix on the filename in conf.d, which load alphabetically.',
  '',
  'map $uri $comparison_redirect {',
  '    default "";',
  ...rows.flatMap((r) => [
    `    # ${r.why}`,
    `    /compare/${r.slug} ${r.redirectTo};`,
    // Astro serves clean URLs; a trailing slash must land in the same place.
    `    /compare/${r.slug}/ ${r.redirectTo};`,
  ]),
  '}',
  '',
];

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`[redirects] wrote ${rows.length} redirects to ${OUT}`);
if (skipped.length) {
  console.log(`[redirects] ${skipped.length} retired without a target (they will 404 unless noindexed in place):`);
  for (const r of skipped) console.log(`            ${r.slug}`);
}
