/**
 * Turns the media rename mapping into an nginx redirect map.
 *
 * Two maps are emitted:
 *
 *   $media_redirect  301 targets for every old media URL, covering both the
 *                    /media/<name> and /api/media/file/<name> prefixes.
 *   $media_gone      410 for the truncated variants crawlers invented when they
 *                    hit an unencoded space — "/media/Belgian Malinois" gets cut
 *                    at the space and refetched as "/media/Belgian".
 *
 * nginx percent-decodes $uri before map lookup, so a single entry per old name
 * matches the raw-space form and the %20-encoded form alike. Keys are quoted
 * because they contain spaces.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = path.resolve(import.meta.dirname, '..');
const MAP_IN = path.join(ROOT, '.cache', 'media-rename-map.tsv');
const OUT = path.join(ROOT, 'deploy', 'nginx-media-redirects.conf');
const PREFIXES = ['/media/', '/api/media/file/'];

const pairs = fs
  .readFileSync(MAP_IN, 'utf8')
  .split('\n')
  .filter(Boolean)
  .map((line) => {
    const [from, to] = line.split('\t');
    return { from, to };
  });

const oldNames = new Set(pairs.map((p) => p.from));
const newNames = new Set(pairs.map((p) => p.to));

/**
 * nginx lowercases map string keys, so two old names differing only in case
 * collide and nginx refuses to start. Where that happens, point the shared key
 * at whichever image is actually referenced by content.
 */
const DB_URL = (() => {
  const env = fs.readFileSync(path.join(ROOT, 'cms', '.env'), 'utf8');
  const line = env.split('\n').find((l) => l.startsWith('DATABASE_URI='));
  return line ? line.slice('DATABASE_URI='.length).trim() : '';
})();

const referenced = new Set<string>(
  DB_URL
    ? execFileSync('psql', [DB_URL, '-tA', '-c',
        'select m.filename from media m where exists (select 1 from breeds b where b.image_id = m.id) ' +
        'or exists (select 1 from comparisons c where c.featured_image_id = m.id)'],
        { encoding: 'utf8' }).split('\n').filter(Boolean)
    : [],
);

const byLowerKey = new Map<string, { from: string; to: string }>();
for (const pair of pairs) {
  const key = pair.from.toLowerCase();
  const existing = byLowerKey.get(key);
  if (!existing) { byLowerKey.set(key, pair); continue; }
  // Keep the referenced image; otherwise first wins.
  if (!referenced.has(existing.to) && referenced.has(pair.to)) byLowerKey.set(key, pair);
  console.warn('  case collision on "' + key + '" -> keeping ' + (byLowerKey.get(key) as any).to);
}
const redirectPairs = [...byLowerKey.values()];

// Every space-delimited prefix of a spaced filename is a URL a truncating
// crawler can produce. Skip any that is itself a real file.
const gone = new Set<string>();
for (const { from } of pairs) {
  if (!from.includes(' ')) continue;
  const words = from.trim().split(/\s+/);
  for (let i = 1; i < words.length; i++) {
    const prefix = words.slice(0, i).join(' ');
    if (!prefix || oldNames.has(prefix) || newNames.has(prefix)) continue;
    gone.add(prefix);
  }
}

const q = (value: string) => '"' + value.replace(/"/g, '\\"') + '"';

const lines: string[] = [
  '# Generated by scripts/generate-media-redirects.ts — do not edit by hand.',
  '# Keys are long file paths, so the default 64-byte hash bucket is too small.',
  'map_hash_bucket_size 256;',
  'map_hash_max_size 4096;',
  '',
  '# Regenerate after any media rename:  npx tsx scripts/generate-media-redirects.ts',
  '#',
  '# nginx decodes $uri before the map runs, so one key covers both the raw-space',
  '# and the %20-encoded form of each old URL.',
  '',
  'map $uri $media_redirect {',
  '    default "";',
];
for (const { from, to } of redirectPairs) {
  for (const prefix of PREFIXES) {
    lines.push('    ' + q(prefix + from) + ' ' + q('/media/' + to) + ';');
  }
}
lines.push('}', '');

lines.push(
  '# Truncated variants invented by crawlers that choked on the unencoded space.',
  '# 410 tells them the URL is permanently gone, which stops the retry loop that',
  '# a plain 404 encourages.',
  'map $uri $media_gone {',
  '    default 0;',
);
for (const prefix of PREFIXES) {
  for (const stub of [...gone].sort()) {
    lines.push('    ' + q(prefix + stub) + ' 1;');
  }
}
lines.push('}', '');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join('\n'));

console.log('redirect entries : ' + redirectPairs.length * PREFIXES.length + ' (' + redirectPairs.length + ' names x ' + PREFIXES.length + ' prefixes)');
console.log('410 stub entries : ' + gone.size * PREFIXES.length + ' (' + gone.size + ' stubs x ' + PREFIXES.length + ' prefixes)');
console.log('written to       : ' + path.relative(ROOT, OUT));
